version: '{build}'
image: Ubuntu2004
skip_tags: true
# branches:
#   only:
#     - master
environment:
  PHP_VER: 8.0
install:
  - sh: nvm install  15.14.0
  - sh: npm -g install npm@7.7.6
  - sh: npm install
before_build:
  - sh: git submodule init
  - sh: git submodule update
before_test:
  - sh: sudo apt --yes install software-properties-common
  - sh: sudo add-apt-repository ppa:ondrej/php
  - sh: sudo apt --yes update
  - sh: sudo apt --yes install php$PHP_VER php$PHP_VER-fpm php$PHP_VER-mysql php$PHP_VER-mbstring php$PHP_VER-zip php$PHP_VER-xml
  - sh: sudo update-alternatives --set php /usr/bin/php$PHP_VER
  - sh: ls -al /var/cache/apt/archives
build_script:
  - sh: npm run build
  - sh: ./dev/update-config.sh $APPVEYOR_REPO_COMMIT
test_script:
  - sh: npm run test
  - sh: ./dev/phpstan.sh
  - sh: ./dev/test.sh

artifacts:
  - path: public_html
    name: public_html
  - path: coverage
    name: coverage

for:
  -
    branches:
      only:
        - master
    deploy_script:
      - sh: cd $APPVEYOR_BUILD_FOLDER/public_html
      - sh: zip -r public_html.zip .
      - sh: $APPVEYOR_BUILD_FOLDER/dev/send.sh

cache:
  - 'node_modules'
  - 'dev/phpstan.phar'
  - '/var/cache/apt/archives'
