version: '{build}'
image: Ubuntu2004
skip_tags: true
# branches:
#   only:
#     - master
environment:
  PHP_VER: 8.0
install:
  - sh: nvm install  15.14.0
  - sh: npm -g install npm@7.7.6
  - sh: npm install
before_build:
  - sh: git submodule init
  - sh: git submodule update
before_test:
  - sh: sudo ./dev/appveyor.sh install /var/ci-package-cache $PHP_VER
build_script:
  - sh: npm run build
  - sh: ./dev/update-config.sh $APPVEYOR_REPO_COMMIT
test_script:
  - sh: npm run test
  - sh: ./dev/phpstan.sh
  - sh: ./dev/test.sh

artifacts:
  - path: public_html
    name: public_html
  - path: coverage
    name: coverage

for:
  -
    branches:
      only:
        - master
    deploy_script:
      - sh: cd $APPVEYOR_BUILD_FOLDER/public_html
      - sh: zip -r public_html.zip .
      - sh: $APPVEYOR_BUILD_FOLDER/dev/send.sh

cache:
  - 'node_modules'
  # - 'dev/phpstan.phar'
