version: '{build}'
image: Ubuntu2004
skip_tags: true
# branches:
#   only:
#     - master
environment:
  PHP_VER: 7.1
install:
  - sh: nvm install  15.14.0
  - sh: npm -g install npm@7.7.6
  - sh: npm install
before_build:
  - sh: git submodule init
  - sh: git submodule update
before_test:
  - sh: sudo apt --yes install software-properties-common
  - sh: sudo add-apt-repository ppa:ondrej/php
  - sh: sudo apt --yes update
  - sh: sudo apt --yes install php$PHP_VER php$PHP_VER-fpm php$PHP_VER-mysql php$PHP_VER-mbstring php$PHP_VER-zip php$PHP_VER-xml
  - sh: sudo update-alternatives --set php /usr/bin/php$PHP_VER
build_script:
  - sh: npm run build
test_script:
  - sh: npm run test
  - sh: cd test; php phpunit --bootstrap ./bootstrap.php --testdox .

artifacts:
  - path: public_html
    name: public_html
  - path: coverage
    name: coverage

# deploy:
#   provider: FTP
#   protocol: ftp
#   host: $FTP_HOST
#   username: $FTP_USER
#   password: $FTP_PASSWD
# #   username:
# #     secure: RQZ2cuCwHoM2UiM/CPowqcm+lRS1qUl6nyfmxti8ZEU=
# #   password:
# #     secure: drLe5anlZHy3VPcn3Xv5uq5WvsMTyxTdn3JtaC7xWM0=
#   folder: /
#   artifact: public_html

# before_deploy:
# #   - sh: sudo apt --yes install openvpn
# #   - sh: curl -o vpn.csv http://www.vpngate.net/api/iphone/
#   - sh: docker run --rm --cap-add=NET_ADMIN --device=/dev/net/tun --dns=1.1.1.1 --dns=8.8.8.8 --dns=9.9.9.9 -p 8118:8118 tantantanuki/ja-vpngate-proxy &
#   - sh: sleep 30
# deploy_script: |
#   lftp <<END
#   debug 5
#   set ftp:proxy http://localhost:8118
#   open ${FTP_USER}:${FTP_PASSWD}@${FTP_HOST}
#   ls
#   lcd public_html
#   mput *.php
#   END

cache:
  - 'node_modules'
