
services:
  www:
    build: ./images/www
    container_name: www-container
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ../
        target: /app
      - type: bind
        source: X:/
        target: /app-data
