name: Build Works

on: push

env:
  php-versions: '8.2'
  extensions: sqlite3, mbstring, zip, xml, gd, xdebug

jobs:
  test-shell:
    name: "<Test> Shell"

    runs-on: ubuntu-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Test> shell
        shell: bash
        run: ./dev/shell-test.sh

  test-shell-os:
    name: "<Test> Shell-OS"
    needs: test-shell

    strategy:
      matrix:
        OS:
          - windows-latest

    runs-on: ${{ matrix.OS }}

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Test> shell
        shell: bash
        run: ./dev/shell-test.sh


  build:
    name: "<Build> Application"
    needs: test-shell

    runs-on: ubuntu-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Add> Node/NPM
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: npm

      - name: <Setup> PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug

      - name: <Install> NPM
        run: npm ci

      - name: <Cache> Phar
        uses: actions/cache@v4
        with:
          path: |
            dev/*.phar.*
            dev/bleedingEdge.neon
            test/*.phar.*
          key: phar-cache-${{ github.job }}-${{ hashFiles('dev/*.sh') }}

      - name: <Build> front-end
        shell: bash
        run: npm run build

      - name: <Build> back-end
        shell: bash
        run: ./dev/update-config.sh ${{ github.sha }}

      - name: <Test> front-end
        shell: bash
        run: npm run test

      - name: <Test> back-end UT/IT
        shell: bash
        run: ./dev/test.sh --mode uit --ignore-namespace

      - name: <Test> back-end cleanup
        shell: bash
        run: ./dev/test-cleanup.sh

      - name: <Generate> document
        shell: bash
        run: ./dev/doc.sh

      - name: <Archive> Application
        shell: bash
        run: tar cfv public_html.tar public_html

      - name: <Artifact> Application
        uses: actions/upload-artifact@v3
        with:
          name: public_html
          path: public_html.tar

  build-matrix:
    name: "<Build> Application(Test)"
    needs: test-shell

    strategy:
      matrix:
        OS:
          - windows-latest
          - ubuntu-latest

    runs-on: ${{ matrix.OS }}

    steps:
      - name: <Setup> Git
        run: git config --global core.autocrlf false

      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Setup> PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug

      - name: <Cache> Phar
        uses: actions/cache@v4
        with:
          path: |
            dev/*.phar.*
            dev/bleedingEdge.neon
            test/*.phar.*
          key: phar-cache-${{ github.job }}-${{ hashFiles('dev/*.sh') }}

      # - name: <Build> back-end
      #   shell: bash
      #   run: ./dev/update-config.sh ${{ github.sha }}

      - name: <Test> code
        shell: bash
        run: ./dev/code.sh

  code-backend:
    name: "<Code> Backend"
    needs: test-shell

    runs-on: ubuntu-latest

    steps:
      - name: <Setup> Git
        run: git config --global core.autocrlf false

      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Setup> PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug

      - name: <Cache> Phar
        uses: actions/cache@v4
        with:
          path: |
            dev/*.phar.*
            dev/bleedingEdge.neon
            test/*.phar.*
          key: phar-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('dev/*.sh') }}

      - name: <Build> back-end
        shell: bash
        run: ./dev/update-config.sh ${{ github.sha }}

      - name: <Test> code
        shell: bash
        run: ./dev/code.sh

  test-backend-st:
    name: "<Test> Backend: ST"
    needs: test-shell

    # strategy:
    #   matrix:
    #     OS:
    #       # - windows-latest
    #       - ubuntu-latest
    #       # - macos-latest

    runs-on: ubuntu-latest

    steps:
      - name: <Setup> Git
        run: git config --global core.autocrlf false

      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Setup> PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug

      - name: <Cache> Phar
        uses: actions/cache@v4
        with:
          path: |
            dev/*.phar.*
            dev/bleedingEdge.neon
            test/*.phar.*
          key: phar-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('dev/*.sh') }}

      - name: <Build> back-end
        shell: bash
        run: ./dev/update-config.sh ${{ github.sha }}

      - name: <Test> back-end ST
        shell: bash
        run: ./dev/test.sh --mode st --ignore-coverage


  deploy:
    name: <Deploy> Application
    needs:
      - build
      - code-backend
      - test-backend-st

    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Download> Application
        uses: actions/download-artifact@v3
        with:
          name: public_html
          path: archive_public_html

      - name: <Expand> Application
        shell: bash
        run: |
          cd archive_public_html
          tar xvf public_html.tar

      - name: <Deploy> Application
        shell: bash
        run: |
          cd archive_public_html/public_html
          zip -r public_html.zip .
          ${{ github.workspace }}/dev/deploy.sh "${{ secrets.PE_SERVER_API_KEY }}" "${{ secrets.PE_SERVER_API_SECRET }}"
