name: "[Daily] Management"

on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Backup
        run: |
          curl \
          -X POST \
          -H "User-Agent: GitHub Actions" \
          -H "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
          -H "X-SECRET-KEY: ${{ secrets.PE_SERVER_API_SECRET }}" \
          https://peserver.gq/api/administrator/backup

      - name: Delete Old Data
        run: |
          curl \
          -X POST \
          -H "User-Agent: GitHub Actions" \
          -H "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
          -H "X-SECRET-KEY: ${{ secrets.PE_SERVER_API_SECRET }}" \
          https://peserver.gq/api/administrator/delete-old-data

      - name: Vacuum Access Log
        run: |
          curl \
          -X POST \
          -H "User-Agent: GitHub Actions" \
          -H "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
          -H "X-SECRET-KEY: ${{ secrets.PE_SERVER_API_SECRET }}" \
          https://peserver.gq/api/administrator/vacuum-access-log

      - name: Rebuild
        run:  |
          curl \
          -X POST \
          -H "User-Agent: GitHub Actions" \
          -H "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
          -H "X-SECRET-KEY: ${{ secrets.PE_SERVER_API_SECRET }}" \
          https://peserver.gq/api/administrator/cache-rebuild

