name: "[Daily] Management"

on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

env:
  PE_SERVER_BASE_URL: https://pe.content-type-text.org

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Backup
        run: |
          curl \
            --request POST \
            --header "User-Agent: GitHub Actions" \
            --header "Referer: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
            --header "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
            --header "X-SECRET-KEY: ${{ secrets.PE_SERVER_API_SECRET }}" \
            ${{ env.PE_SERVER_BASE_URL }}/api/administrator/backup

      - name: Delete Old Data
        run: |
          curl \
            --request POST \
            --header "User-Agent: GitHub Actions" \
            --header "Referer: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
            --header "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
            --header "X-SECRET-KEY: ${{ secrets.PE_SERVER_API_SECRET }}" \
            ${{ env.PE_SERVER_BASE_URL }}/api/administrator/delete-old-data

      - name: Vacuum Access Log
        run: |
          curl \
            --request POST \
            --header "User-Agent: GitHub Actions" \
            --header "Referer: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
            --header "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
            --header "X-SECRET-KEY: ${{ secrets.PE_SERVER_API_SECRET }}" \
            ${{ env.PE_SERVER_BASE_URL }}/api/administrator/vacuum-access-log

      - name: Rebuild
        run:  |
          curl \
            --request POST \
            --header "User-Agent: GitHub Actions" \
            --header "Referer: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
            --header "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
            --header "X-SECRET-KEY: ${{ secrets.PE_SERVER_API_SECRET }}" \
            ${{ env.PE_SERVER_BASE_URL }}/api/administrator/cache-rebuild

