name: \[Cron] Daily

# on:
#   schedule:
#     - cron: "0 0 * * *"
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 1!
        run: |
          curl \
          -H "X-API-KEY: ${{ secrets.PE_SERVER_API_KEY }}" \
          https://peserver.gq/api/administrator/backup

      - name: 2!
        run:  https://peserver.gq/api/administrator/cache-rebuild

