name: \[Cron] Daily

# on:
#   schedule:
#     - cron: "0 0 * * *"
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 1!
        run:  echo "1"

      - name: 2!
        run:  echo "2"

